name: 'Install docker-pussh'
description: 'Installs the docker-pussh plugin for Docker CLI'
author: 'Reza Kargar'
inputs:
  version:
    description: 'Version to install (e.g. v1.0.0 or "latest"). Defaults to "latest"'
    required: false
    default: 'latest'

runs:
  using: 'composite'
  steps:
    - id: entrypoint
      name: Run entrypoint.sh
      run: entrypoint.sh
      shell: bash
      env:
        INPUT_VERSION: ${{ inputs.version }}